# Generated by Django 5.1.1 on 2025-01-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_alter_establishment_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='type',
            field=models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink')], max_length=100),
        ),
    ]
